package config

var (
	CtrlA = string([]byte{1})
	CtrlB = string([]byte{2})
	CtrlC = string([]byte{3})
	CtrlD = string([]byte{4})
	CtrlE = string([]byte{5})
	CtrlF = string([]byte{6})
	CtrlG = string([]byte{7})
	CtrlH = string([]byte{8})
	CtrlI = string([]byte{9})
	CtrlJ = string([]byte{10})
	CtrlK = string([]byte{11})
	CtrlL = string([]byte{12})
	CtrlM = string([]byte{13})
	CtrlN = string([]byte{14})
	CtrlO = string([]byte{15})
	CtrlP = string([]byte{16})
	CtrlQ = string([]byte{17})
	CtrlR = string([]byte{18})
	CtrlS = string([]byte{19})
	CtrlT = string([]byte{20})
	CtrlU = string([]byte{21})
	CtrlV = string([]byte{22})
	CtrlW = string([]byte{23})
	CtrlX = string([]byte{24})
	CtrlY = string([]byte{25})
	CtrlZ = string([]byte{26})

	ShiftTab = string([]byte{27, 91, 90})
)
